apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
resources:
  - service-account.yaml
  - cluster-role-binding.yaml
  - helm-repository.yaml
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: redis-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
