apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cassandra
resources:
  - service-account.yaml
  - cluster-role-binding.yaml
  - helm-repository.yaml
  - namespace.yaml
  - release.yaml
