apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cassandra
spec:
  releaseName: cassandra
  chart:
    spec:
      chart: cassandra
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cassandra
      #version: "9.2.6"
  interval: 1h0m0s
  url: https://charts.bitnami.com/bitnami
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    replicaCount: 3
    service:
      type: LoadBalancer
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s
