apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: galera
spec:
  releaseName: galera
  chart:
    spec:
      chart: mariadb-galera
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      #version: "9.2.6"
  interval: 0h1m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/cassandra

